services:
  db:
    image: postgres:16-alpine
    container_name: patientform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patientdb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
